export const wrapper: string = 'grid col-span-full justify-items-center p-16';
export const container: string = 'grid grid-cols-2 gap-4 sm:grid-cols-3 w-[1020px]';
export const card: string = 'p-4 border border-2 border-white rounded-md shadow-sm cursor-pointer';
export const title: string = 'font-(family-name:--font-kanit-sans) text-7xl font-bold mb-4 uppercase';
export const subTitle: string = 'text-center text-2xl font-bold mb-8';
export const form: string = 'w-[500px] rounded-xl border-2 border-white p-10 dot-shadow bg-[#181818]';
export const label: string = 'w-full mb-4 inline-block';
export const input: string = 'text-black w-full mb-10 p-3 rounded-xl bg-white';
export const button: string = 'rounded-full bg-white text-black pt-3 pb-3 pl-6 pr-6 font-bold block mx-auto';
